version: '{build}'
os: Windows Server 2012

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - cmd: java -version
  - cmd: mvn clean compile assembly:single install --settings mvnsettings.xml -DOTN_USERNAME=%OTN_USERNAME% -DOTN_PASSWORD=%OTN_PASSWORD%
test: off
artifacts:
